const fs=require('fs'),path=require('path'),cp=require('child_process');
const file=process.argv[2]||'index.html'; const root=path.dirname(path.resolve(file)); const s=fs.readFileSync(file,'utf8');
let pass=true; function check(name,ok,detail){console.log((ok?'PASS':'FAIL')+' '+name+' — '+detail);if(!ok)pass=false}
const scripts=[...s.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi)].map(m=>m[1]);
scripts.forEach((js,i)=>{const f=path.join('/tmp',`bt_guard_${process.pid}_${i}.js`);fs.writeFileSync(f,js);const r=cp.spawnSync('node',['--check',f],{encoding:'utf8'});check('JS構文 #'+(i+1),r.status===0,r.status===0?'OK':r.stderr.trim())});
const ids=[...s.matchAll(/\bid=["']([^"']+)["']/g)].map(m=>m[1]);check('重複ID',new Set(ids).size===ids.length,'OK');
const fn=[...s.matchAll(/function\s+([A-Za-z_$][\w$]*)\s*\(/g)].map(m=>m[1]);check('重複した名前付きfunction',new Set(fn).size===fn.length,'OK');
check('localStorage.clear() 不使用',!s.includes('localStorage.clear('),'OK');
check('4.11.3 Visual Baseline',/4\.11\.3.*Visual Baseline|Visual Baseline.*4\.11\.3/i.test(s+fs.readFileSync(path.join(root,'SPEC.md'),'utf8')),'OK');
check('APP_VERSION 4.12.7',/APP_VERSION\s*=\s*["']4\.12\.7["']/.test(s),'OK');
check('DEMO_ENABLED 定義',/DEMO_ENABLED\s*=/.test(s),'OK');
check('正規登録関数',/window\.addBook|window\.bulkAdd/.test(s),'OK');
check('全選択は checkbox',/id="libAll"[^>]*type="checkbox"/.test(s),'OK');
check('購入状態の直接代入を禁止',!/getMeta\([^)]*\)\.purchaseStatus\s*=/.test(s),'OK');
check('仕様文書',fs.existsSync(path.join(root,'SPEC.md'))&&fs.existsSync(path.join(root,'DEV_GUARD.md')),'OK');
check('ステータス固定幅',s.includes('.library-status-stack{')&&s.includes('width:78px;min-width:78px')&&s.includes('.series-title-status-stack{')&&s.includes('box-sizing:border-box;width:78px'),'78px');
check('折りたたみ状態保持',/seriesOpenKey|setSeriesOpenState/.test(s)&&/data-series-open/.test(s),'OK');
check('タイトル一覧戻るUI',/series-title-collapse\{[^}]*background:transparent!important/.test(s),'元表示');
check('5冊以上シリーズ積層',/series-stack-14/.test(s)&&/translateY\(1px\)/.test(s)&&/translateY\(14px\)/.test(s),'15枚・縦1pxずつ');
check('5冊以上タイトル行背景',/\.series-group\.is-cyclic \.series-cyclic-head\{[^}]*background:color-mix\(in srgb,var\(--primary\) 8%,var\(--surface\)\)!important/.test(s)&&/\.series-group\.is-cyclic \.series-cyclic-title\{[^}]*color:var\(--app-text\)!important/.test(s),'5冊以上のみ背景色を少し濃く');
process.exit(pass?0:1);
